import { 
  Truck, Shield, Clock, ChevronRight, Star, 
  CheckCircle, ArrowRight, Phone, Mail, MapPin,
  Facebook, Twitter, Instagram, Youtube, HelpCircle,
  TrendingUp, Users, Award, Battery, Cpu, ShoppingBag,
  Menu, Heart, ShoppingCart, Search, Zap, Headphones,
  Monitor, Smartphone, Tablet, Camera, GamepadIcon,
  Watch, Speaker, Keyboard, Mouse, Wifi, Bluetooth,
  CreditCard, Package, RefreshCw, DollarSign, Globe,
  ShieldCheck, BatteryCharging, Thermometer, CpuIcon,
  HardDrive, MemoryStick, Sparkles, Gift, Tag,
  Calendar, User, ThumbsUp, MessageSquare, Eye,
  ShoppingBasket, Home, Info, FileText, Settings,
  Lock, HelpCircle as Help, ExternalLink
} from "lucide-react";





export const products = [
  {
    id: 1,
    title: 'Gaming Laptop',
    slug: 'gaming-laptop',
    price: 1299,
    rating: 5,
    brand: 'Asus',
    reviewCount: 40,
    originalPrice: 1499,
    category: ['Laptop'],
    discount: 200,
    colors: ['Black', 'Gray'],
    storageOptions: ['512GB SSD', '1TB SSD'],
    image: '/images/laptop.jpg',
    images: ['/images/laptop.jpg', '/images/laptop.jpg', '/images/laptop2.jpg'],
    specs: ['Intel i7', '16GB RAM', 'RTX 4060']
  },
  {
    id: 2,
    title: 'Smartphone Pro',
    slug: 'smartphone-pro',
    price: 899,
    rating: 4,
    brand: 'Apple',
    reviewCount: 128,
    originalPrice: 999,
    category: ['Smartphone'],
    discount: 100,
    colors: ['Black', 'Silver', 'Blue'],
    storageOptions: ['128GB', '256GB', '512GB'],
    image: '/images/phone.jpg',
    images: ['/images/phone.jpg', '/images/phone2.jpg'],
    specs: ['OLED', '5G', '128GB']
  },
  {
    id: 3,
    title: 'Smartwatch',
    slug: 'smartwatch',
    price: 299,
    rating: 3,
    brand: 'Samsung',
    reviewCount: 56,
    originalPrice: 349,
    category: ['Wearable'],
    discount: 50,
    colors: ['Black', 'Silver', 'Pink'],
    storageOptions: ['8GB', '16GB'],
    image: '/images/watch.jpg',
    images: ['/images/watch.jpg', '/images/watch2.jpg'],
    specs: ['GPS', 'Heart Rate', 'Waterproof']
  },
  {
    id: 4,
    title: 'Headphones',
    slug: 'headphones',
    price: 199,
    rating: 4,
    brand: 'Sony',
    reviewCount: 89,
    originalPrice: 249,
    category: ['Audio'],
    discount: 50,
    colors: ['Black', 'White'],
    storageOptions: ['N/A'],
    image: '/images/headphone.jpg',
    images: ['/images/headphone.jpg', '/images/headphones2.jpg'],
    specs: ['Bluetooth', 'Noise Canceling', 'Wireless']
  },
  {
    id: 5,
    title: 'Camera',
    slug: 'camera',
    price: 599,
    rating: 5,
    brand: 'Canon',
    reviewCount: 72,
    originalPrice: 699,
    category: ['Camera'],
    discount: 100,
    colors: ['Black'],
    storageOptions: ['SD Card Slot'],
    image: '/images/camera.jpeg',
    images: ['/images/camera.jpeg', '/images/camera2.jpg'],
    specs: ['4K', '24MP', 'F/1.8 Aperture']
  },
  {
    id: 6,
    title: 'Gaming Console',
    slug: 'gaming-console',
    price: 499,
    rating: 4,
    brand: 'Sony',
    reviewCount: 210,
    originalPrice: 549,
    category: ['Gaming'],
    discount: 50,
    colors: ['White'],
    storageOptions: ['825GB SSD', '1TB SSD'],
    image: '/images/game-console.webp',
    images: ['/images/game-console.webp', '/images/game-console2.jpg'],
    specs: ['PS5', '8GB RAM', 'SSD']
  },
  {
    id: 7,
    title: 'Ultrabook',
    slug: 'laptop',
    price: 999,
    rating: 4,
    brand: 'Dell',
    reviewCount: 45,
    originalPrice: 1199,
    category: ['Laptop'],
    discount: 200,
    colors: ['Silver', 'Gray'],
    storageOptions: ['512GB SSD', '1TB SSD'],
    image: '/images/laptop.avif',
    images: ['/images/laptop.avif', '/images/laptop2.jpg'],
    specs: ['Intel i7', '16GB RAM', 'RTX 4060']
  },
  {
    id: 8,
    title: 'Mechanical Keyboard',
    slug: 'mechanical-keyboard',
    price: 149,
    rating: 5,
    brand: 'Razer',
    reviewCount: 92,
    originalPrice: 179,
    category: ['Accessories'],
    discount: 30,
    colors: ['Black', 'White', 'RGB'],
    storageOptions: ['N/A'],
    image: '/images/mechanicalkey.jpeg',
    images: ['/images/mechanicalkey.jpeg', '/images/mechanicalkey.jpeg'],
    specs: ['RGB', 'Mechanical Keys', 'USB-C']
  },
  {
    id: 9,
    title: 'Wireless Mouse',
    slug: 'wireless-mouse',
    price: 79,
    rating: 4,
    brand: 'Logitech',
    reviewCount: 67,
    originalPrice: 99,
    category: ['Accessories'],
    discount: 20,
    colors: ['Black', 'White', 'Gray'],
    storageOptions: ['N/A'],
    image: '/images/mouse.jpeg',
    images: ['/images/mouse.jpeg', '/images/mouse.jpeg'],
    specs: ['Ergonomic', 'Rechargeable', '16000 DPI']
  },
  {
    id: 10,
    title: '4K Monitor',
    slug: '4k-monitor',
    price: 399,
    rating: 5,
    brand: 'LG',
    reviewCount: 84,
    originalPrice: 499,
    category: ['Monitor'],
    discount: 100,
    colors: ['Black'],
    storageOptions: ['N/A'],
    image: '/images/monitor.jpeg',
    images: ['/images/monitor.jpeg', '/images/monitor2.jpg'],
    specs: ['27 Inch', 'IPS', '144Hz']
  },
  {
    id: 11,
    title: 'Bluetooth Speaker',
    slug: 'bluetooth-speaker',
    price: 129,
    rating: 4,
    brand: 'JBL',
    reviewCount: 120,
    originalPrice: 159,
    category: ['Audio'],
    discount: 30,
    colors: ['Black', 'Blue', 'Red'],
    storageOptions: ['N/A'],
    image: '/images/bspeaker.jpeg',
    images: ['/images/bspeaker.jpeg', '/images/speaker2.jpg'],
    specs: ['Bass Boost', 'Portable', '12H Battery']
  },
  {
    id: 12,
    title: 'VR Headset',
    slug: 'vr-headset',
    price: 499,
    rating: 5,
    brand: 'Meta',
    reviewCount: 56,
    originalPrice: 599,
    category: ['Gaming', 'VR'],
    discount: 100,
    colors: ['White', 'Black'],
    storageOptions: ['128GB', '256GB'],
    image: '/images/vr.jpeg',
    images: ['/images/vr.jpeg', '/images/vr2.jpg'],
    specs: ['4K', 'Motion Tracking', 'Wireless']
  }
];

export const categories = [
  { id: 1, name: "Gaming Laptops", icon: Monitor, count: 245, color: "bg-purple-100", textColor: "text-purple-600" },
  { id: 2, name: "Smartphones", icon: Smartphone, count: 189, color: "bg-blue-100", textColor: "text-blue-600" },
  { id: 3, name: "Tablets", icon: Tablet, count: 98, color: "bg-green-100", textColor: "text-green-600" },
  { id: 4, name: "Gaming Consoles", icon: GamepadIcon, count: 67, color: "bg-red-100", textColor: "text-red-600" },
  { id: 5, name: "Smart Watches", icon: Watch, count: 134, color: "bg-cyan-100", textColor: "text-cyan-600" },
  { id: 6, name: "Headphones", icon: Headphones, count: 156, color: "bg-orange-100", textColor: "text-orange-600" },
  { id: 7, name: "Speakers", icon: Speaker, count: 89, color: "bg-pink-100", textColor: "text-pink-600" },
  { id: 8, name: "Keyboards", icon: Keyboard, count: 112, color: "bg-indigo-100", textColor: "text-indigo-600" },
  { id: 9, name: "Mice", icon: Mouse, count: 95, color: "bg-gray-100", textColor: "text-gray-600" },
  { id: 10, name: "Cameras", icon: Camera, count: 76, color: "bg-yellow-100", textColor: "text-yellow-600" },
  { id: 11, name: "Monitors", icon: Monitor, count: 103, color: "bg-teal-100", textColor: "text-teal-600" },
  { id: 12, name: "Drones", icon: Zap, count: 45, color: "bg-rose-100", textColor: "text-rose-600" },
];

export const blogPosts = [
  { 
    id: 1, 
    title: "The Future of Gaming: Ray Tracing & AI Integration", 
    excerpt: "Discover how ray tracing and AI are revolutionizing the gaming industry in 2024.",
    author: "Alex Chen",
    date: "Mar 15, 2024",
    readTime: "5 min read",
    category: "Gaming",
    image: "/images/blog/gaming-future.jpg",
    views: "12.5K"
  },
  { 
    id: 2, 
    title: "Smartphone Camera Wars: Which Tech Reigns Supreme?", 
    excerpt: "Comparing the latest smartphone camera technologies from leading manufacturers.",
    author: "Maria Rodriguez",
    date: "Mar 10, 2024",
    readTime: "7 min read",
    category: "Mobile Tech",
    image: "/images/blog/camera-tech.jpg",
    views: "8.7K"
  },
  { 
    id: 3, 
    title: "Sustainable Tech: Eco-Friendly Gadgets You'll Love", 
    excerpt: "Exploring environmentally conscious tech products that don't compromise on performance.",
    author: "David Kim",
    date: "Mar 5, 2024",
    readTime: "6 min read",
    category: "Sustainability",
    image: "/images/blog/eco-tech.jpg",
    views: "15.2K"
  },
  { 
    id: 4, 
    title: "Building Your First PC: A Complete Beginner's Guide", 
    excerpt: "Step-by-step guide to building a custom PC without breaking the bank.",
    author: "Tech Pro Team",
    date: "Feb 28, 2024",
    readTime: "12 min read",
    category: "DIY",
    image: "/images/blog/pc-build.jpg",
    views: "25.8K"
  },
  { 
    id: 5, 
    title: "Wireless Revolution: The Rise of Bluetooth 5.3", 
    excerpt: "How Bluetooth 5.3 is changing connectivity standards across all devices.",
    author: "Sarah Johnson",
    date: "Feb 22, 2024",
    readTime: "4 min read",
    category: "Wireless Tech",
    image: "/images/blog/bluetooth-5.jpg",
    views: "9.3K"
  },
  { 
    id: 6, 
    title: "Laptop Battery Health: Maintenance Tips & Tricks", 
    excerpt: "Extend your laptop's battery life with these proven maintenance techniques.",
    author: "Michael Brown",
    date: "Feb 18, 2024",
    readTime: "8 min read",
    category: "Hardware",
    image: "/images/blog/battery-health.jpg",
    views: "18.4K"
  },
  { 
    id: 7, 
    title: "VR Gaming: The Next Level of Immersive Experience", 
    excerpt: "Exploring the latest developments in virtual reality gaming technology.",
    author: "Lisa Wang",
    date: "Feb 12, 2024",
    readTime: "6 min read",
    category: "VR/AR",
    image: "/images/blog/vr-gaming.jpg",
    views: "11.7K"
  },
  { 
    id: 8, 
    title: "Smart Home Integration: Creating Your Connected Space", 
    excerpt: "How to seamlessly integrate all your smart devices for optimal home automation.",
    author: "Robert Miller",
    date: "Feb 8, 2024",
    readTime: "9 min read",
    category: "Smart Home",
    image: "/images/blog/smart-home.jpg",
    views: "14.9K"
  },
  { 
    id: 9, 
    title: "Audio Tech: From Hi-Res to Spatial Audio", 
    excerpt: "Understanding the different audio technologies and what they mean for listeners.",
    author: "Audio Expert Team",
    date: "Feb 3, 2024",
    readTime: "7 min read",
    category: "Audio",
    image: "/images/blog/audio-tech.jpg",
    views: "7.6K"
  },
  { 
    id: 10, 
    title: "The Evolution of Gaming Consoles: Past to Future", 
    excerpt: "Tracing the journey of gaming consoles and predicting what's next.",
    author: "James Wilson",
    date: "Jan 29, 2024",
    readTime: "10 min read",
    category: "Gaming",
    image: "/images/blog/consoles-evolution.jpg",
    views: "22.3K"
  },
  { 
    id: 11, 
    title: "Cybersecurity for Smart Devices: Essential Protection", 
    excerpt: "Keeping your connected devices safe from modern cyber threats.",
    author: "Security Team",
    date: "Jan 25, 2024",
    readTime: "8 min read",
    category: "Security",
    image: "/images/blog/cybersecurity.jpg",
    views: "13.8K"
  },
  { 
    id: 12, 
    title: "The Rise of Foldable Phones: Worth the Investment?", 
    excerpt: "Analyzing whether foldable phones deliver on their promise and are worth buying.",
    author: "Emma Thompson",
    date: "Jan 20, 2024",
    readTime: "6 min read",
    category: "Mobile Tech",
    image: "/images/blog/foldable-phones.jpg",
    views: "16.5K"
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Michael Rodriguez",
    role: "Gaming Enthusiast",
    rating: 4.9,
    content: "The gaming laptop I purchased exceeded all expectations. The build quality is outstanding and performance is smooth even on max settings. Customer service was incredibly helpful when I had questions about upgrades.",
    date: "2 days ago",
    avatar: "/images/avatars/avatar1.svg",
    verified: true
  },
  {
    id: 2,
    name: "Sarah Johnson",
    role: "Graphic Designer",
    rating: 5.0,
    content: "As a professional designer, I need reliable equipment. The tablet I bought here has transformed my workflow. The color accuracy is perfect and the stylus responsiveness is unmatched.",
    date: "1 week ago",
    avatar: "/images/avatars/avatar2.svg",
    verified: true
  },
  {
    id: 3,
    name: "David Chen",
    role: "Software Developer",
    rating: 4.8,
    content: "Great selection of mechanical keyboards. Found exactly what I was looking for. Shipping was fast and packaging was secure. Will definitely shop here again for my tech needs.",
    date: "2 weeks ago",
    avatar: "/images/avatars/avatar3.svg",
    verified: true
  },
  {
    id: 4,
    name: "Lisa Wang",
    role: "Student",
    rating: 4.7,
    content: "Affordable prices for quality tech. The student discount made my laptop purchase possible. Battery life is excellent for all-day classes.",
    date: "3 weeks ago",
    avatar: "/images/avatars/avatar4.svg",
    verified: true
  }
];

export const brands = [
  { id: 1, name: "Apple", logo: "/images/brands/apple.svg", products: 245, featured: true },
  { id: 2, name: "Samsung", logo: "/images/brands/samsung.svg", products: 189, featured: true },
  { id: 3, name: "Dell", logo: "/images/brands/dell.svg", products: 156, featured: true },
  { id: 4, name: "HP", logo: "/images/brands/hp.svg", products: 134, featured: true },
  { id: 5, name: "Lenovo", logo: "/images/brands/lenovo.svg", products: 128, featured: true },
  { id: 6, name: "ASUS", logo: "/images/brands/asus.svg", products: 112, featured: true },
  { id: 7, name: "MSI", logo: "/images/brands/msi.svg", products: 89, featured: false },
  { id: 8, name: "Razer", logo: "/images/brands/razer.svg", products: 76, featured: false },
  { id: 9, name: "Logitech", logo: "/images/brands/logitech.svg", products: 145, featured: true },
  { id: 10, name: "Sony", logo: "/images/brands/sony.svg", products: 98, featured: true },
  // { id: 11, name: "Bose", logo: "/images/brands/bose.svg", products: 67, featured: false },
  // { id: 12, name: "JBL", logo: "/images/brands/jbl.svg", products: 54, featured: false },
  // { id: 13, name: "Canon", logo: "/images/brands/canon.svg", products: 76, featured: true },
  // { id: 14, name: "Nikon", logo: "/images/brands/nikon.svg", products: 65, featured: false },
  // { id: 15, name: "Xiaomi", logo: "/images/brands/xiaomi.svg", products: 89, featured: false },
];

export const features = [
  { id: 1, icon: Truck, title: "Free Shipping", description: "On orders over ₹99", color: "bg-blue-500" },
  { id: 2, icon: Shield, title: "2-Year Warranty", description: "Extended protection", color: "bg-green-500" },
  { id: 3, icon: Clock, title: "30-Day Returns", description: "Hassle-free process", color: "bg-purple-500" },
  { id: 4, icon: CreditCard, title: "Secure Payment", description: "100% safe transactions", color: "bg-red-500" },
  { id: 5, icon: Package, title: "Fast Delivery", description: "1-3 business days", color: "bg-orange-500" },
  { id: 6, icon: RefreshCw, title: "Easy Returns", description: "Simple return process", color: "bg-cyan-500" },
  { id: 7, icon: DollarSign, title: "Price Match", description: "Best price guarantee", color: "bg-yellow-500" },
  { id: 8, icon: Globe, title: "Worldwide Shipping", description: "International delivery", color: "bg-indigo-500" },
  { id: 9, icon: ShieldCheck, title: "Authentic Products", description: "Genuine brands only", color: "bg-emerald-500" },
  { id: 10, icon: Users, title: "Expert Support", description: "24/7 customer service", color: "bg-pink-500" },
];

export const techSpecs = [
  { id: 1, icon: CpuIcon, label: "Processor", value: "Intel Core i9-13900HX" },
  { id: 2, icon: MemoryStick, label: "RAM", value: "32GB DDR5" },
  { id: 3, icon: HardDrive, label: "Storage", value: "2TB NVMe SSD" },
  { id: 4, icon: BatteryCharging, label: "Battery", value: "99Wh (Up to 8 hours)" },
  { id: 5, icon: Thermometer, label: "Cooling", value: "Vapor Chamber + Dual Fans" },
  { id: 6, icon: Monitor, label: "Display", value: '16" QHD+ 240Hz' },
  { id: 7, icon: Zap, label: "Graphics", value: "NVIDIA RTX 4070 8GB" },
  { id: 8, icon: Wifi, label: "Connectivity", value: "Wi-Fi 6E + Bluetooth 5.3" },
  { id: 9, icon: Keyboard, label: "Keyboard", value: "Per-key RGB Mechanical" },
  { id: 10, icon: Mouse, label: "Ports", value: "Thunderbolt 4, HDMI 2.1, USB-C" },
];

export const faqs = [
  { id: 1, question: "What is your return policy?", answer: "We offer a 30-day return policy for all unopened and unused items in original packaging." },
  { id: 2, question: "How long does shipping take?", answer: "Standard shipping takes 3-5 business days, express shipping takes 1-2 business days." },
  { id: 3, question: "Do you offer international shipping?", answer: "Yes, we ship to over 50 countries worldwide with various shipping options." },
  { id: 4, question: "Are the products covered by warranty?", answer: "All products come with at least 1-year manufacturer warranty, some have extended coverage." },
  { id: 5, question: "Can I cancel my order?", answer: "Orders can be cancelled within 1 hour of placement or before they ship." },
  { id: 6, question: "Do you offer student discounts?", answer: "Yes, students get 10% off with valid student ID verification." },
  { id: 7, question: "How do I track my order?", answer: "Tracking information is sent via email once your order ships." },
  { id: 8, question: "What payment methods do you accept?", answer: "We accept all major credit cards, PayPal, Apple Pay, Google Pay, and bank transfers." },
  { id: 9, question: "Do you price match competitors?", answer: "Yes, we offer price matching on identical products from authorized retailers." },
  { id: 10, question: "Can I change my shipping address?", answer: "Address changes are possible before the order ships. Contact support immediately." },
];